matrivume/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html')),
]

matrivume_profile/urls.py
from django.urls import path
from matrivume_profile import views

app_name = 'matrivume_profile'

urlpatterns = [
    path('', views.profile_view, name="profile_view"),
    path('update/', views.profile_update_view, name="profile_update_view"),
    path('registrations/', views.user_registration_view, name="registration"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

matrivume_profile/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.dispatch import receiver

User = get_user_model()

# Create your models here.
# Todo: To add ancestry app we will add (Father, Mother, GrandFather, ProGrandFather)
# Todo: To add an app for our team information
# Todo: To add app for Blogging
# Todo: To add app for Social Networking
# Todo: Instead of asking directly we will make feature like imei.info


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Identity(models.Model):
    user_profile = models.OneToOneField(User, on_delete=models.CASCADE, related_name="identity_user")
    birth_date = models.DateField(null=True, blank=True)
    '''
    weight = models.PositiveSmallIntegerField(null=True, blank=True)
    height = models.FloatField(null=True, blank=True)
    '''

    '''
    trade_license_number = models.CharField(max_length=255, null=True, blank=True)
    tax_identification_number = models.CharField(max_length=255, null=True, blank=True)
    student_id = models.CharField(max_length=255, null=True, blank=True)
    '''

    '''
    passport_number = models.CharField(max_length=255, null=True, blank=True)
    national_identity = models.CharField(max_length=255, null=True, blank=True)
    birth_certificate = models.CharField(max_length=255, null=True, blank=True)
    cell_phone_number = models.CharField(max_length=50, null=True, blank=True)
    '''

    github_profile_link = models.URLField(null=True, blank=True)
    bio = models.TextField(default="No bio")
    # profile_picture = models.ImageField(upload_to='') when we make login system we will make it

    # cell_phone_imei_code = models.CharField(max_length=50, null=True, blank=True)

    # education_profile = we will add educational profile :)
    # address = we are going use the google's maps API :)

    def __str__(self):
        return self.user_profile.username

matrivume_profile/forms.py
from django import forms
from matrivume_profile import models


class LoginForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, min_length=8, max_length=100)


class IdentityForm(forms.ModelForm):
    birth_date = forms.CharField(required=False, widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = models.Identity
        exclude = ('user_profile', 'id')

matrivume_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from matrivume_profile.forms import LoginForm, IdentityForm
from matrivume_profile import models
# Create your views here.

User = get_user_model()


def user_registration_view(request):
    if request.method == 'POST':
        print("Just doing")
        form = UserCreationForm(request.POST)

        if form.is_valid():
            print(form.cleaned_data)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = User.objects.create_user(username=username, password=password)
            identity = models.Identity.objects.create(user_profile=user)
            identity.save()

            return HttpResponseRedirect(reverse('matrivume_profile:login'))

    form = UserCreationForm()
    return render(request, "matrivume_profile/registration.html", {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user=user)
                return HttpResponseRedirect(reverse('home'))
    form = LoginForm()
    return render(request, "matrivume_profile/login.html", {'form': form})


@login_required()
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('matrivume_profile:login'))


@login_required()
def profile_view(request):
    profile_model = models.Identity.objects.filter(user_profile=request.user).first()
    context = {
        'profile': profile_model
    }
    return render(request, 'matrivume_profile/profile.html', context=context)


@login_required()
def profile_update_view(request):
    profile_model = models.Identity.objects.filter(user_profile=request.user).first()
    if request.method == 'POST':
        form = IdentityForm(data=request.POST)

        if form.is_valid():
            birth_date = form.cleaned_data['birth_date']
            github_profile_link = form.cleaned_data['github_profile_link']
            bio = form.cleaned_data['bio']
            profile_model.birth_date = birth_date
            profile_model.github_profile_link = github_profile_link
            profile_model.bio = bio
            profile_model.save()
            return HttpResponseRedirect(reverse('matrivume_profile:profile_view'))

    form = IdentityForm(initial={
        'birth_date': profile_model.birth_date,
        'github_profile_link': profile_model.github_profile_link,
        'bio': profile_model.bio
    })
    context = {
        'form': form,
        'profile': profile_model
    }
    return render(request, 'matrivume_profile/profile.html', context=context)

matrivume_profile/templates/matrivume_profile/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
    <form action="{% url 'matrivume_profile:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

matrivume_profile/templates/matrivume_profile/profile.html
{% extends "base.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
{{ profile.user_profile }}
<a href="{{ profile.github_profile_link }}">Github</a>
{% if form %}
<form action="{% url 'matrivume_profile:profile_update_view' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endif %}
{% endblock %}

matrivume_profile/templates/matrivume_profile/registration.html
{% extends "base.html" %}
{% block title %}Registration{% endblock %}

{% block content %}
    <form action="{% url 'matrivume_profile:registration' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Matrivume | {% block title %}{% endblock %}</title>
</head>
<body>
    {% if request.user.is_authenticated %}
    <a href="{% url 'matrivume_profile:logout' %}">logout</a>
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>matrivume</title>
</head>
<body>
<h1>Our Founding Member</h1>
<hr>
    <h1>Sushen Biswas</h1>
    <h1>Fahim Al Islam</h1>
    <h1>Nosin Ibna Mahbub</h1>
    <h1>Zabir Hasan</h1>
    <h1>A. H. Tushar</h1>
    <h1>Biplob Hasan Nibir</h1>
    <h1>Debashis Gupta</h1>
    <h1>Sajib Hossain</h1>
    <h1>Shariar Ashfaq Turin</h1>
    <h1>Shafayet Sadi</h1>


    <h1>Md Robin Hassan</h1>
    <h1></h1>

    <hr>
    <ul>
        <li><a href="{% url 'matrivume_profile:profile_view' %}">Profile</a></li>
        <li><a href="{% url 'matrivume_profile:profile_update_view' %}">Profile Update</a></li>

    </ul>
<h1></h1>
</body>
</html>